qanda/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "articles#index"
  root "questions#index"
  resources :questions do
    resources :answers
  end
end

qanda/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

qanda/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

qanda/app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  
  validates :title, presence: true
  validates :name, presence: true
  validates :content, presence: true, length: { minimum: 5 }
end

qanda/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # 回答の登録
  def create
    # p params
    @question = Question.find(params[:question_id])
    @question.answers.create(answer_params)
    redirect_to question_path(@question)
  end
  
  # 回答の削除
  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to @question, status: :see_other
  end
  
  private
  def answer_params
    params.require(:answer).permit(:name, :content)
  end
  
end

qanda/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

qanda/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # 質問一覧表示
  def index
    @questions = Question.all
    p @questions
  end
  
  # 質問詳細ページ表示
  def show
    p params[:id]
    @question = Question.find(params[:id])
    # p @question
  end
  
  # 質問の作成
  def new
    @question = Question.new
  end

  # 質問の登録
  def create
    # Questionモデルを初期化
    @question = Question.new(questions_params)
    # QuestionモデルをDBへ保存
    if @question.save
      # showへリダイレクト
      redirect_to @question
    else
      render 'new', status: :unprocessable_entity
    end
  end
  
  # 質問の編集
  def edit
    @question = Question.find(params[:id])
  end

  # 質問の更新
  def update
    @question = Question.find(params[:id])
    if @question.update(questions_params)
      redirect_to @question
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  # 質問の削除
  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end
  
  private
  def questions_params
    params.require(:question).permit(:title, :name, :content)
  end
end

qanda/app/helpers/answers_helper.rb
module AnswersHelper
end

qanda/app/helpers/application_helper.rb
module ApplicationHelper
end

qanda/app/helpers/questions_helper.rb
module QuestionsHelper
end

qanda/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qanda</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

qanda/app/views/questions/_form.html.erb
<%= form_with model: @question do |form| %>
  <% if @question.errors.any? %>
    <div>
      <ul>
        <% @question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
  <%= form.label :name %><br>
  <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

qanda/app/views/questions/edit.html.erb
<h1>Edit</h1>
<%= render partial: 'form' %>

qanda/app/views/questions/index.html.erb
<h1>Questions</h1>
<%= link_to 'new', new_question_path %>
<table>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Name</th>
      <th>Content</th>
      <th></th>
    </tr>
    <% @questions.each do |question| %>
    <tr>
        <td><%= question.id =%></td>
        <td><%= question.title =%></td>
        <td><%= question.name =%></td>
        <td><%= question.content =%></td>
        <td><%= link_to 'show', question_path(question) =%></td>
        <td><%= link_to 'edit', edit_question_path(question) =%></td>
        <td><%= link_to 'destroy', question_path(question),
              data: { turbo_method: 'delete', turbo_confirm: 'Are you sure?' }%></td>
    </tr>
    <% end %>
</table>

qanda/app/views/questions/new.html.erb
<h1>New question</h1>
<%= form_with model: @question do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
  <%= form.label :name %><br>
  <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

qanda/app/views/questions/show.html.erb
<h1>Show</h1>
<P>
  Title:<br>
  <%= @question.title %>
</P>

<P>
  Name:<br>
  <%= @question.name %>
</P>

<P>
  Content:<br>
  <%= @question.content %>
</P>

<h2>Answers</h2>
<% @question.answers.each do |answer| %>
  <p>
    Name:<br>
    <%= answer.name %>
  </p>
  <p>
    Content:<br>
    <%= answer.content %>
  </p>
  <p>
    <%= link_to 'Destroy Answer', [answer.question, answer],
      data: { turbo_method: 'delete', turbo_confirm: 'Are you sure?' } %>
  </p>
<% end %>

<h2>Add a answer</h2>
<%= form_with model: [@question, @question.answers.build] do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'top', questions_path %>